live_config_reload = true

[cursor]
unfocused_hollow = false

[font]
size = 7.5

[font.bold]
family = "SFMono"
style = "Heavy"

[font.glyph_offset]
y = 0

[font.normal]
family = "SFMono"
style = "Regular"

[window]
opacity = 0.94

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 20
y = 10
#tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#0d1114"
foreground = "#b2b2b2"

[colors.bright]
black = "#4a565c"
blue = "#7a94ba"
cyan = "#76c0c7"
green = "#81c3a3"
magenta = "#89707c"
red = "#e58386"
white = "#d0d0d0"
yellow = "#b7a781"

[colors.normal]
black = "#2c383e"
blue = "#5c769c"
cyan = "#58a2a9"
green = "#63a585"
magenta = "#6b525e"
red = "#c76568"
white = "#b2b2b2"
yellow = "#998963"

[[colors.indexed_colors]]
color = "#B3836B"
index = 16

[[colors.indexed_colors]]
color = "#8fa398"
index = 17

[[colors.indexed_colors]]
color = "#7FA891"
index = 18

[[colors.indexed_colors]]
color = "#89b2a8"
index = 19

[[colors.indexed_colors]]
color = "#807773"
index = 20

[[colors.indexed_colors]]
color = "#5f6a73"
index = 21

[[colors.indexed_colors]]
color = "#756367"
index = 22

[[colors.indexed_colors]]
color = "#b2adae"
index = 23

[[colors.indexed_colors]]
color = "#1a1f20"
index = 24

[[colors.indexed_colors]]
color = "#252b2c"
index = 25

[[colors.indexed_colors]]
color = "#3d4445"
index = 26

[[colors.indexed_colors]]
color = "#c8a789"
index = 27

[[colors.indexed_colors]]
color = "#191720"
index = 28

[[colors.indexed_colors]]
color = "#23212c"
index = 29

[[colors.indexed_colors]]
color = "#3a3745"
index = 30

[[colors.indexed_colors]]
color = "#f2b599"
index = 31

[[colors.indexed_colors]]
color = "#201e1f"
index = 32

[[colors.indexed_colors]]
color = "#2c2a2b"
index = 33

[[colors.indexed_colors]]
color = "#454545"
index = 34

[[colors.indexed_colors]]
color = "#ad7361"
index = 35

[[colors.indexed_colors]]
color = "#0d201f"
index = 36

[[colors.indexed_colors]]
color = "#132c2b"
index = 37

[[colors.indexed_colors]]
color = "#214544"
index = 38

[[colors.indexed_colors]]
color = "#d45957"
index = 39

[[colors.indexed_colors]]
color = "#1c1c20"
index = 40

[[colors.indexed_colors]]
color = "#28282c"
index = 41

[[colors.indexed_colors]]
color = "#424245"
index = 42

[[colors.indexed_colors]]
color = "#e34e68"
index = 43

[[colors.indexed_colors]]
color = "#172020"
index = 44

[[colors.indexed_colors]]
color = "#212c2c"
index = 45

[[colors.indexed_colors]]
color = "#374545"
index = 46

[[colors.indexed_colors]]
color = "#a07479"
index = 47

[[colors.indexed_colors]]
color = "#0c201f"
index = 48

[[colors.indexed_colors]]
color = "#112c2b"
index = 49

[[colors.indexed_colors]]
color = "#1e4544"
index = 50

[[colors.indexed_colors]]
color = "#dd5d64"
index = 51

[[colors.indexed_colors]]
color = "#0f1720"
index = 52

[[colors.indexed_colors]]
color = "#15202c"
index = 53

[[colors.indexed_colors]]
color = "#243445"
index = 54

[[colors.indexed_colors]]
color = "#ca7b7c"
index = 55

[[colors.indexed_colors]]
color = "#191f20"
index = 56

[[colors.indexed_colors]]
color = "#232b2c"
index = 57

[[colors.indexed_colors]]
color = "#3a4445"
index = 58

[[colors.indexed_colors]]
color = "#ac8e75"
index = 59

[[colors.indexed_colors]]
color = "#191d20"
index = 60

[[colors.indexed_colors]]
color = "#23282c"
index = 61

[[colors.indexed_colors]]
color = "#3a4045"
index = 62

[[colors.indexed_colors]]
color = "#9e8f80"
index = 63

[[colors.indexed_colors]]
color = "#1f2020"
index = 64

[[colors.indexed_colors]]
color = "#2c2c2c"
index = 65

[[colors.indexed_colors]]
color = "#be5879"
index = 66

[[colors.indexed_colors]]
color = "#121a20"
index = 67

[[colors.indexed_colors]]
color = "#1a242c"
index = 68

[[colors.indexed_colors]]
color = "#2c3a45"
index = 69

[[colors.indexed_colors]]
color = "#f05171"
index = 70

[[colors.indexed_colors]]
color = "#1e1e20"
index = 71

[[colors.indexed_colors]]
color = "#2a2a2c"
index = 72

[[colors.indexed_colors]]
color = "#d15cb4"
index = 73

[[colors.indexed_colors]]
color = "#cdb3af"
index = 74

[[colors.indexed_colors]]
color = "#1d1c20"
index = 75

[[colors.indexed_colors]]
color = "#29282c"
index = 76

[[colors.indexed_colors]]
color = "#434245"
index = 77

[[colors.indexed_colors]]
color = "#c8929c"
index = 78

[[colors.indexed_colors]]
color = "#ffb771"
index = 79

[[colors.indexed_colors]]
color = "#201d19"
index = 80

[[colors.indexed_colors]]
color = "#2c2823"
index = 81

[[colors.indexed_colors]]
color = "#45403a"
index = 82

[[colors.indexed_colors]]
color = "#c7ae84"
index = 83

[[colors.indexed_colors]]
color = "#201e1e"
index = 84

[[colors.indexed_colors]]
color = "#2c2a2a"
index = 85

[[colors.indexed_colors]]
color = "#d3bd72"
index = 86

[[colors.indexed_colors]]
color = "#121520"
index = 87

[[colors.indexed_colors]]
color = "#1a1e2c"
index = 88

[[colors.indexed_colors]]
color = "#2c3245"
index = 89

[[colors.indexed_colors]]
color = "#feb672"
index = 90

[[colors.indexed_colors]]
color = "#ffb871"
index = 91

[[colors.indexed_colors]]
color = "#1c2020"
index = 92

[[colors.indexed_colors]]
color = "#282c2c"
index = 93

[[colors.indexed_colors]]
color = "#424545"
index = 94

[[colors.indexed_colors]]
color = "#ff858f"
index = 95

[[colors.indexed_colors]]
color = "#20201c"
index = 96

[[colors.indexed_colors]]
color = "#2c2c28"
index = 97

[[colors.indexed_colors]]
color = "#454542"
index = 98

[[colors.indexed_colors]]
color = "#cf7277"
index = 99

[[colors.indexed_colors]]
color = "#171720"
index = 100

[[colors.indexed_colors]]
color = "#21212c"
index = 101

[[colors.indexed_colors]]
color = "#373745"
index = 102

[[colors.indexed_colors]]
color = "#bc626a"
index = 103

[[colors.indexed_colors]]
color = "#201c20"
index = 104

[[colors.indexed_colors]]
color = "#2c282c"
index = 105

[[colors.indexed_colors]]
color = "#454245"
index = 106

[[colors.indexed_colors]]
color = "#7ec197"
index = 107

[[colors.indexed_colors]]
color = "#201f20"
index = 108

[[colors.indexed_colors]]
color = "#e2557c"
index = 109

[[colors.indexed_colors]]
color = "#aca979"
index = 110

[[colors.indexed_colors]]
color = "#1f1f20"
index = 111

[[colors.indexed_colors]]
color = "#201212"
index = 112

[[colors.indexed_colors]]
color = "#2c1a1a"
index = 113

[[colors.indexed_colors]]
color = "#523636"
index = 114

[[colors.indexed_colors]]
color = "#a2c89a"
index = 115

[[colors.indexed_colors]]
color = "#152020"
index = 116

[[colors.indexed_colors]]
color = "#1e2c2c"
index = 117

[[colors.indexed_colors]]
color = "#3d5252"
index = 118

[[colors.indexed_colors]]
color = "#5daeb3"
index = 119

[[colors.indexed_colors]]
color = "#435252"
index = 120

[[colors.indexed_colors]]
color = "#799ec3"
index = 121

[[colors.indexed_colors]]
color = "#1f201f"
index = 122

[[colors.indexed_colors]]
color = "#525252"
index = 123

[[colors.indexed_colors]]
color = "#4a5152"
index = 124

[[colors.indexed_colors]]
color = "#201d1c"
index = 125

[[colors.indexed_colors]]
color = "#2c2928"
index = 126

[[colors.indexed_colors]]
color = "#525050"
index = 127

[[colors.indexed_colors]]
color = "#8ba9b3"
index = 128

[[colors.indexed_colors]]
color = "#a4d7ed"
index = 129

[[colors.indexed_colors]]
color = "#171920"
index = 130

[[colors.indexed_colors]]
color = "#21232c"
index = 131

[[colors.indexed_colors]]
color = "#434652"
index = 132

[[colors.indexed_colors]]
color = "#5d96af"
index = 133

[[colors.indexed_colors]]
color = "#a59d94"
index = 134

[[colors.indexed_colors]]
color = "#988f85"
index = 135

[[colors.indexed_colors]]
color = "#71675b"
index = 136

[[colors.indexed_colors]]
color = "#545d62"
index = 137

[[colors.indexed_colors]]
color = "#a59ea5"
index = 138

[[colors.indexed_colors]]
color = "#988e98"
index = 139

[[colors.indexed_colors]]
color = "#716271"
index = 140

[[colors.indexed_colors]]
color = "#151c20"
index = 141

[[colors.indexed_colors]]
color = "#1e272c"
index = 142

[[colors.indexed_colors]]
color = "#3d4a52"
index = 143

[[colors.indexed_colors]]
color = "#63a585"
index = 144

[[colors.indexed_colors]]
color = "#070606"
index = 145

[[colors.indexed_colors]]
color = "#000000"
index = 146

[[colors.indexed_colors]]
color = "#000000"
index = 147

[[colors.indexed_colors]]
color = "#000000"
index = 148

[[colors.indexed_colors]]
color = "#000000"
index = 149

[[colors.indexed_colors]]
color = "#000000"
index = 150

[[colors.indexed_colors]]
color = "#000000"
index = 151

[[colors.indexed_colors]]
color = "#000000"
index = 152

[[colors.indexed_colors]]
color = "#000000"
index = 153

[[colors.indexed_colors]]
color = "#000000"
index = 154

[[colors.indexed_colors]]
color = "#000000"
index = 155

[[colors.indexed_colors]]
color = "#000000"
index = 156

[[colors.indexed_colors]]
color = "#000000"
index = 157

[[colors.indexed_colors]]
color = "#000000"
index = 158

[[colors.indexed_colors]]
color = "#1c1f20"
index = 159

[[colors.indexed_colors]]
color = "#282b2c"
index = 160

[[colors.indexed_colors]]
color = "#505152"
index = 161

[[colors.indexed_colors]]
color = "#9381a8"
index = 162

[[colors.indexed_colors]]
color = "#505052"
index = 163

[[colors.indexed_colors]]
color = "#829b9b"
index = 164

[[colors.indexed_colors]]
color = "#606970"
index = 165

[[colors.indexed_colors]]
color = "#201514"
index = 166

[[colors.indexed_colors]]
color = "#2c1e1c"
index = 167

[[colors.indexed_colors]]
color = "#523d3a"
index = 168

[[colors.indexed_colors]]
color = "#95a9c8"
index = 169

[[colors.indexed_colors]]
color = "#111120"
index = 170

[[colors.indexed_colors]]
color = "#18182c"
index = 171

[[colors.indexed_colors]]
color = "#323252"
index = 172

[[colors.indexed_colors]]
color = "#86a4ae"
index = 173

[[colors.indexed_colors]]
color = "#201a11"
index = 174

[[colors.indexed_colors]]
color = "#2c2418"
index = 175

[[colors.indexed_colors]]
color = "#524532"
index = 176

[[colors.indexed_colors]]
color = "#7ca0a2"
index = 177

[[colors.indexed_colors]]
color = "#201f1f"
index = 178

[[colors.indexed_colors]]
color = "#7f7b7c"
index = 179

[[colors.indexed_colors]]
color = "#6f5760"
index = 180

[[colors.indexed_colors]]
color = "#20201f"
index = 181

[[colors.indexed_colors]]
color = "#688f96"
index = 182

[[colors.indexed_colors]]
color = "#201814"
index = 183

[[colors.indexed_colors]]
color = "#2c221c"
index = 184

[[colors.indexed_colors]]
color = "#52433a"
index = 185

[[colors.indexed_colors]]
color = "#58a2a9"
index = 186

[[colors.indexed_colors]]
color = "#151a20"
index = 187

[[colors.indexed_colors]]
color = "#1e242c"
index = 188

[[colors.indexed_colors]]
color = "#3d4652"
index = 189

[[colors.indexed_colors]]
color = "#c6b595"
index = 190

[[colors.indexed_colors]]
color = "#a676c8"
index = 191

[[colors.indexed_colors]]
color = "#201120"
index = 192

[[colors.indexed_colors]]
color = "#2c182c"
index = 193

[[colors.indexed_colors]]
color = "#523252"
index = 194

[[colors.indexed_colors]]
color = "#e56639"
index = 195

[[colors.indexed_colors]]
color = "#1a1c20"
index = 196

[[colors.indexed_colors]]
color = "#25272c"
index = 197

[[colors.indexed_colors]]
color = "#4a4d52"
index = 198

[[colors.indexed_colors]]
color = "#b471b4"
index = 199

[[colors.indexed_colors]]
color = "#56a5b8"
index = 200

[[colors.indexed_colors]]
color = "#20201e"
index = 201

[[colors.indexed_colors]]
color = "#2c2c2a"
index = 202

[[colors.indexed_colors]]
color = "#ba5b77"
index = 203

[[colors.indexed_colors]]
color = "#1f1c20"
index = 204

[[colors.indexed_colors]]
color = "#2b282c"
index = 205

[[colors.indexed_colors]]
color = "#515052"
index = 206

[[colors.indexed_colors]]
color = "#bfac5d"
index = 207

[[colors.indexed_colors]]
color = "#121c20"
index = 208

[[colors.indexed_colors]]
color = "#1a272c"
index = 209

[[colors.indexed_colors]]
color = "#364a52"
index = 210

[[colors.indexed_colors]]
color = "#97c999"
index = 211

[[colors.indexed_colors]]
color = "#64a2ae"
index = 212

[[colors.indexed_colors]]
color = "#141c20"
index = 213

[[colors.indexed_colors]]
color = "#1c272c"
index = 214

[[colors.indexed_colors]]
color = "#3a4a52"
index = 215

[[colors.indexed_colors]]
color = "#5d94a3"
index = 216

[[colors.indexed_colors]]
color = "#878f85"
index = 217

[[colors.indexed_colors]]
color = "#5c5e96"
index = 218

[[colors.indexed_colors]]
color = "#6d969b"
index = 219

[[colors.indexed_colors]]
color = "#6c808c"
index = 220

[[colors.indexed_colors]]
color = "#ff3c60"
index = 221

[[colors.indexed_colors]]
color = "#674b5e"
index = 222

[[colors.indexed_colors]]
color = "#89a3a0"
index = 223

[[colors.indexed_colors]]
color = "#d25aa6"
index = 224

[[colors.indexed_colors]]
color = "#201f1c"
index = 225

[[colors.indexed_colors]]
color = "#2c2b28"
index = 226

[[colors.indexed_colors]]
color = "#525150"
index = 227

[[colors.indexed_colors]]
color = "#c1a2c1"
index = 228

[[colors.indexed_colors]]
color = "#111420"
index = 229

[[colors.indexed_colors]]
color = "#181c2c"
index = 230

[[colors.indexed_colors]]
color = "#323852"
index = 231

[[colors.indexed_colors]]
color = "#c54f8b"
index = 232

[[colors.indexed_colors]]
color = "#43c49f"
index = 233

[[colors.indexed_colors]]
color = "#201f17"
index = 234

[[colors.indexed_colors]]
color = "#2c2b21"
index = 235

[[colors.indexed_colors]]
color = "#525043"
index = 236

[[colors.indexed_colors]]
color = "#9b9a9b"
index = 237

[[colors.indexed_colors]]
color = "#201414"
index = 238

[[colors.indexed_colors]]
color = "#2c1c1c"
index = 239

[[colors.indexed_colors]]
color = "#523a3a"
index = 240

[[colors.indexed_colors]]
color = "#111d20"
index = 241

[[colors.indexed_colors]]
color = "#18282c"
index = 242

[[colors.indexed_colors]]
color = "#293f45"
index = 243

[[colors.indexed_colors]]
color = "#84a9a4"
index = 244

[[colors.indexed_colors]]
color = "#ca6577"
index = 245

[[colors.indexed_colors]]
color = "#859e7c"
index = 246

[[colors.indexed_colors]]
color = "#3d4045"
index = 247

[[colors.indexed_colors]]
color = "#6ba29f"
index = 248

[[colors.indexed_colors]]
color = "#45372f"
index = 249
