general.live_config_reload = true

[cursor]
unfocused_hollow = false
style = "Beam"

[font]
size = 7

[font.bold]
family = "SFMono"
style = "Heavy"

[font.glyph_offset]
y = 0

[font.normal]
family = "SFMono"
style = "Regular"

[window]
opacity = 1.00

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 20
y = 15

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#1c1c1c"
foreground = "#a59c9c"

[colors.bright]
black = "#646464"
blue = "#66667c"
cyan = "#bbeadb"
green = "#9db1a3"
magenta = "#f19aa5"
red = "#ed8275"
white = "#c3baba"
yellow = "#fff0cd"

[colors.normal]
black = "#464646"
blue = "#48485e"
cyan = "#9dccbd"
green = "#7f9385"
magenta = "#d37c87"
red = "#cf6457"
white = "#a59c9c"
yellow = "#e8d2af"

[[colors.indexed_colors]]
color = "#B3836B"
index = 16

[[colors.indexed_colors]]
color = "#8fa398"
index = 17

[[colors.indexed_colors]]
color = "#282828"
index = 18

[[colors.indexed_colors]]
color = "#343434"
index = 19

[[colors.indexed_colors]]
color = "#5a5a5a"
index = 20

[[colors.indexed_colors]]
color = "#5daca3"
index = 21

[[colors.indexed_colors]]
color = "#281b1b"
index = 22

[[colors.indexed_colors]]
color = "#342424"
index = 23

[[colors.indexed_colors]]
color = "#5a4444"
index = 24

[[colors.indexed_colors]]
color = "#86a98c"
index = 25

[[colors.indexed_colors]]
color = "#282423"
index = 26

[[colors.indexed_colors]]
color = "#34302f"
index = 27

[[colors.indexed_colors]]
color = "#4d4a49"
index = 28

[[colors.indexed_colors]]
color = "#5badaa"
index = 29

[[colors.indexed_colors]]
color = "#b5d6d1"
index = 30

[[colors.indexed_colors]]
color = "#1d2128"
index = 31

[[colors.indexed_colors]]
color = "#272c34"
index = 32

[[colors.indexed_colors]]
color = "#4a505a"
index = 33

[[colors.indexed_colors]]
color = "#9acfd3"
index = 34

[[colors.indexed_colors]]
color = "#3e434d"
index = 35

[[colors.indexed_colors]]
color = "#222828"
index = 36

[[colors.indexed_colors]]
color = "#2d3434"
index = 37

[[colors.indexed_colors]]
color = "#464d4d"
index = 38

[[colors.indexed_colors]]
color = "#547f7c"
index = 39

[[colors.indexed_colors]]
color = "#282622"
index = 40

[[colors.indexed_colors]]
color = "#34322d"
index = 41

[[colors.indexed_colors]]
color = "#4d4b46"
index = 42

[[colors.indexed_colors]]
color = "#282223"
index = 43

[[colors.indexed_colors]]
color = "#342d2f"
index = 44

[[colors.indexed_colors]]
color = "#4d4648"
index = 45

[[colors.indexed_colors]]
color = "#6790c3"
index = 46

[[colors.indexed_colors]]
color = "#0b1a28"
index = 47

[[colors.indexed_colors]]
color = "#0f2234"
index = 48

[[colors.indexed_colors]]
color = "#1a344d"
index = 49

[[colors.indexed_colors]]
color = "#97d8d8"
index = 50

[[colors.indexed_colors]]
color = "#282020"
index = 51

[[colors.indexed_colors]]
color = "#342b2b"
index = 52

[[colors.indexed_colors]]
color = "#4d4343"
index = 53

[[colors.indexed_colors]]
color = "#50c2a5"
index = 54

[[colors.indexed_colors]]
color = "#232826"
index = 55

[[colors.indexed_colors]]
color = "#2f3432"
index = 56

[[colors.indexed_colors]]
color = "#494d4c"
index = 57

[[colors.indexed_colors]]
color = "#bac49b"
index = 58

[[colors.indexed_colors]]
color = "#62954d"
index = 59

[[colors.indexed_colors]]
color = "#688768"
index = 60

[[colors.indexed_colors]]
color = "#281d1f"
index = 61

[[colors.indexed_colors]]
color = "#342729"
index = 62

[[colors.indexed_colors]]
color = "#4d3e40"
index = 63

[[colors.indexed_colors]]
color = "#9d7f9c"
index = 64

[[colors.indexed_colors]]
color = "#28261b"
index = 65

[[colors.indexed_colors]]
color = "#343224"
index = 66

[[colors.indexed_colors]]
color = "#4d4b39"
index = 67

[[colors.indexed_colors]]
color = "#858f91"
index = 68

[[colors.indexed_colors]]
color = "#1d0f28"
index = 69

[[colors.indexed_colors]]
color = "#261434"
index = 70

[[colors.indexed_colors]]
color = "#3a214d"
index = 71

[[colors.indexed_colors]]
color = "#ff7d9c"
index = 72

[[colors.indexed_colors]]
color = "#10ffd9"
index = 73

[[colors.indexed_colors]]
color = "#4d4a49"
index = 74

[[colors.indexed_colors]]
color = "#aad893"
index = 75

[[colors.indexed_colors]]
color = "#87876b"
index = 76

[[colors.indexed_colors]]
color = "#282322"
index = 77

[[colors.indexed_colors]]
color = "#342f2d"
index = 78

[[colors.indexed_colors]]
color = "#4d4846"
index = 79

[[colors.indexed_colors]]
color = "#7f9182"
index = 80

[[colors.indexed_colors]]
color = "#4d4d4d"
index = 81

[[colors.indexed_colors]]
color = "#7ea79f"
index = 82

[[colors.indexed_colors]]
color = "#7a9186"
index = 83

[[colors.indexed_colors]]
color = "#93b0a9"
index = 84

[[colors.indexed_colors]]
color = "#507070"
index = 85

[[colors.indexed_colors]]
color = "#89b7a1"
index = 86

[[colors.indexed_colors]]
color = "#8bb8af"
index = 87

[[colors.indexed_colors]]
color = "#828b85"
index = 88

[[colors.indexed_colors]]
color = "#90bba3"
index = 89

[[colors.indexed_colors]]
color = "#7d8f84"
index = 90

[[colors.indexed_colors]]
color = "#93bba2"
index = 91

[[colors.indexed_colors]]
color = "#7f9385"
index = 92

[[colors.indexed_colors]]
color = "#94c0b0"
index = 93
