live_config_reload = true

[cursor]
unfocused_hollow = false
style = "Beam"

[font]
size = 7.5

[font.bold]
#family = "Iosevka Orw"
family = "SFMono"
style = "Heavy"

[font.glyph_offset]
y = 0

[font.normal]
family = "SFMono"
style = "Regular"

[window]
opacity = 1.00

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 20
y = 15
#tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#0a0f14"
foreground = "#d8d8d8"

[colors.bright]
black = "#8fa1ae"
blue = "#aebee1"
cyan = "#cde2f6"
green = "#888997"
magenta = "#b598c3"
red = "#9f797d"
white = "#f6f6f6"
yellow = "#ecbeb2"

[colors.normal]
black = "#718390"
blue = "#90a0c3"
cyan = "#afc4d8"
green = "#6a6b79"
magenta = "#977aa5"
red = "#815b5f"
white = "#d8d8d8"
yellow = "#cea094"

[[colors.indexed_colors]]
color = "#B3836B"
index = 16

[[colors.indexed_colors]]
color = "#8fa398"
index = 17

[[colors.indexed_colors]]
color = "#7FA891"
index = 18

[[colors.indexed_colors]]
color = "#89b2a8"
index = 19

[[colors.indexed_colors]]
color = "#807773"
index = 20

[[colors.indexed_colors]]
color = "#5f6a73"
index = 21

[[colors.indexed_colors]]
color = "#756367"
index = 22

[[colors.indexed_colors]]
color = "#b2adae"
index = 23

[[colors.indexed_colors]]
color = "#1a1f20"
index = 24

[[colors.indexed_colors]]
color = "#252b2c"
index = 25

[[colors.indexed_colors]]
color = "#3d4445"
index = 26

[[colors.indexed_colors]]
color = "#c8a789"
index = 27

[[colors.indexed_colors]]
color = "#191720"
index = 28

[[colors.indexed_colors]]
color = "#23212c"
index = 29

[[colors.indexed_colors]]
color = "#3a3745"
index = 30

[[colors.indexed_colors]]
color = "#f2b599"
index = 31

[[colors.indexed_colors]]
color = "#201e1f"
index = 32

[[colors.indexed_colors]]
color = "#2c2a2b"
index = 33

[[colors.indexed_colors]]
color = "#454545"
index = 34

[[colors.indexed_colors]]
color = "#ad7361"
index = 35

[[colors.indexed_colors]]
color = "#0d201f"
index = 36

[[colors.indexed_colors]]
color = "#132c2b"
index = 37

[[colors.indexed_colors]]
color = "#214544"
index = 38

[[colors.indexed_colors]]
color = "#d45957"
index = 39

[[colors.indexed_colors]]
color = "#1c1c20"
index = 40

[[colors.indexed_colors]]
color = "#28282c"
index = 41

[[colors.indexed_colors]]
color = "#424245"
index = 42

[[colors.indexed_colors]]
color = "#e34e68"
index = 43

[[colors.indexed_colors]]
color = "#172020"
index = 44

[[colors.indexed_colors]]
color = "#212c2c"
index = 45

[[colors.indexed_colors]]
color = "#374545"
index = 46

[[colors.indexed_colors]]
color = "#a07479"
index = 47

[[colors.indexed_colors]]
color = "#0c201f"
index = 48

[[colors.indexed_colors]]
color = "#112c2b"
index = 49

[[colors.indexed_colors]]
color = "#1e4544"
index = 50

[[colors.indexed_colors]]
color = "#dd5d64"
index = 51

[[colors.indexed_colors]]
color = "#0f1720"
index = 52

[[colors.indexed_colors]]
color = "#15202c"
index = 53

[[colors.indexed_colors]]
color = "#243445"
index = 54

[[colors.indexed_colors]]
color = "#ca7b7c"
index = 55

[[colors.indexed_colors]]
color = "#191f20"
index = 56

[[colors.indexed_colors]]
color = "#232b2c"
index = 57

[[colors.indexed_colors]]
color = "#3a4445"
index = 58

[[colors.indexed_colors]]
color = "#ac8e75"
index = 59

[[colors.indexed_colors]]
color = "#191d20"
index = 60

[[colors.indexed_colors]]
color = "#23282c"
index = 61

[[colors.indexed_colors]]
color = "#3a4045"
index = 62

[[colors.indexed_colors]]
color = "#9e8f80"
index = 63

[[colors.indexed_colors]]
color = "#1f2020"
index = 64

[[colors.indexed_colors]]
color = "#2c2c2c"
index = 65

[[colors.indexed_colors]]
color = "#be5879"
index = 66

[[colors.indexed_colors]]
color = "#121a20"
index = 67

[[colors.indexed_colors]]
color = "#1a242c"
index = 68

[[colors.indexed_colors]]
color = "#2c3a45"
index = 69

[[colors.indexed_colors]]
color = "#f05171"
index = 70

[[colors.indexed_colors]]
color = "#1e1e20"
index = 71

[[colors.indexed_colors]]
color = "#2a2a2c"
index = 72

[[colors.indexed_colors]]
color = "#d15cb4"
index = 73

[[colors.indexed_colors]]
color = "#cdb3af"
index = 74

[[colors.indexed_colors]]
color = "#1d1c20"
index = 75

[[colors.indexed_colors]]
color = "#29282c"
index = 76

[[colors.indexed_colors]]
color = "#434245"
index = 77

[[colors.indexed_colors]]
color = "#c8929c"
index = 78

[[colors.indexed_colors]]
color = "#ffb771"
index = 79

[[colors.indexed_colors]]
color = "#201d19"
index = 80

[[colors.indexed_colors]]
color = "#2c2823"
index = 81

[[colors.indexed_colors]]
color = "#45403a"
index = 82

[[colors.indexed_colors]]
color = "#c7ae84"
index = 83

[[colors.indexed_colors]]
color = "#201e1e"
index = 84

[[colors.indexed_colors]]
color = "#2c2a2a"
index = 85

[[colors.indexed_colors]]
color = "#d3bd72"
index = 86

[[colors.indexed_colors]]
color = "#121520"
index = 87

[[colors.indexed_colors]]
color = "#1a1e2c"
index = 88

[[colors.indexed_colors]]
color = "#2c3245"
index = 89

[[colors.indexed_colors]]
color = "#feb672"
index = 90

[[colors.indexed_colors]]
color = "#ffb871"
index = 91

[[colors.indexed_colors]]
color = "#1c2020"
index = 92

[[colors.indexed_colors]]
color = "#282c2c"
index = 93

[[colors.indexed_colors]]
color = "#424545"
index = 94

[[colors.indexed_colors]]
color = "#ff858f"
index = 95

[[colors.indexed_colors]]
color = "#20201c"
index = 96

[[colors.indexed_colors]]
color = "#2c2c28"
index = 97

[[colors.indexed_colors]]
color = "#454542"
index = 98

[[colors.indexed_colors]]
color = "#cf7277"
index = 99

[[colors.indexed_colors]]
color = "#171720"
index = 100

[[colors.indexed_colors]]
color = "#21212c"
index = 101

[[colors.indexed_colors]]
color = "#373745"
index = 102

[[colors.indexed_colors]]
color = "#bc626a"
index = 103

[[colors.indexed_colors]]
color = "#201c20"
index = 104

[[colors.indexed_colors]]
color = "#2c282c"
index = 105

[[colors.indexed_colors]]
color = "#454245"
index = 106

[[colors.indexed_colors]]
color = "#7ec197"
index = 107

[[colors.indexed_colors]]
color = "#201f20"
index = 108

[[colors.indexed_colors]]
color = "#e2557c"
index = 109

[[colors.indexed_colors]]
color = "#aca979"
index = 110

[[colors.indexed_colors]]
color = "#1f1f20"
index = 111

[[colors.indexed_colors]]
color = "#1f201a"
index = 112

[[colors.indexed_colors]]
color = "#2b2c25"
index = 113

[[colors.indexed_colors]]
color = "#44453d"
index = 114

[[colors.indexed_colors]]
color = "#c1bb99"
index = 115

[[colors.indexed_colors]]
color = "#1e2020"
index = 116

[[colors.indexed_colors]]
color = "#2a2c2c"
index = 117

[[colors.indexed_colors]]
color = "#5e9775"
index = 118

[[colors.indexed_colors]]
color = "#121d20"
index = 119

[[colors.indexed_colors]]
color = "#1a282c"
index = 120

[[colors.indexed_colors]]
color = "#2c3f45"
index = 121

[[colors.indexed_colors]]
color = "#769bb3"
index = 122

[[colors.indexed_colors]]
color = "#11201c"
index = 123

[[colors.indexed_colors]]
color = "#182c27"
index = 124

[[colors.indexed_colors]]
color = "#29453e"
index = 125

[[colors.indexed_colors]]
color = "#b65555"
index = 126

[[colors.indexed_colors]]
color = "#ad808c"
index = 127

[[colors.indexed_colors]]
color = "#111f20"
index = 128

[[colors.indexed_colors]]
color = "#182b2c"
index = 129

[[colors.indexed_colors]]
color = "#294445"
index = 130

[[colors.indexed_colors]]
color = "#5ca4c1"
index = 131

[[colors.indexed_colors]]
color = "#152020"
index = 132

[[colors.indexed_colors]]
color = "#1e2c2c"
index = 133

[[colors.indexed_colors]]
color = "#324545"
index = 134

[[colors.indexed_colors]]
color = "#5b6c7c"
index = 135

[[colors.indexed_colors]]
color = "#111820"
index = 136

[[colors.indexed_colors]]
color = "#18222c"
index = 137

[[colors.indexed_colors]]
color = "#293745"
index = 138

[[colors.indexed_colors]]
color = "#6c7563"
index = 139

[[colors.indexed_colors]]
color = "#12201f"
index = 140

[[colors.indexed_colors]]
color = "#1a2c2b"
index = 141

[[colors.indexed_colors]]
color = "#2c4544"
index = 142

[[colors.indexed_colors]]
color = "#577a5c"
index = 143

[[colors.indexed_colors]]
color = "#201c12"
index = 144

[[colors.indexed_colors]]
color = "#2c271a"
index = 145

[[colors.indexed_colors]]
color = "#453e2c"
index = 146

[[colors.indexed_colors]]
color = "#7f94a3"
index = 147

[[colors.indexed_colors]]
color = "#111720"
index = 148

[[colors.indexed_colors]]
color = "#18202c"
index = 149

[[colors.indexed_colors]]
color = "#293445"
index = 150

[[colors.indexed_colors]]
color = "#5c7474"
index = 151

[[colors.indexed_colors]]
color = "#4c7356"
index = 152

[[colors.indexed_colors]]
color = "#192020"
index = 153

[[colors.indexed_colors]]
color = "#232c2c"
index = 154

[[colors.indexed_colors]]
color = "#3a4545"
index = 155

[[colors.indexed_colors]]
color = "#598585"
index = 156

[[colors.indexed_colors]]
color = "#73858a"
index = 157

[[colors.indexed_colors]]
color = "#5e8166"
index = 158

[[colors.indexed_colors]]
color = "#111c20"
index = 159

[[colors.indexed_colors]]
color = "#18272c"
index = 160

[[colors.indexed_colors]]
color = "#293e45"
index = 161

[[colors.indexed_colors]]
color = "#c4bd91"
index = 162

[[colors.indexed_colors]]
color = "#517e85"
index = 163

[[colors.indexed_colors]]
color = "#bb3a6f"
index = 164

[[colors.indexed_colors]]
color = "#8f8fad"
index = 165

[[colors.indexed_colors]]
color = "#bcbc9e"
index = 166

[[colors.indexed_colors]]
color = "#53647b"
index = 167

[[colors.indexed_colors]]
color = "#55696e"
index = 168

[[colors.indexed_colors]]
color = "#638386"
index = 169

[[colors.indexed_colors]]
color = "#9797be"
index = 170

[[colors.indexed_colors]]
color = "#588a91"
index = 171

[[colors.indexed_colors]]
color = "#d6427f"
index = 172

[[colors.indexed_colors]]
color = "#ff4669"
index = 173

[[colors.indexed_colors]]
color = "#1c1d20"
index = 174

[[colors.indexed_colors]]
color = "#28292c"
index = 175

[[colors.indexed_colors]]
color = "#424345"
index = 176

[[colors.indexed_colors]]
color = "#56bdb7"
index = 177

[[colors.indexed_colors]]
color = "#201f1f"
index = 178

[[colors.indexed_colors]]
color = "#525252"
index = 179

[[colors.indexed_colors]]
color = "#98b3ba"
index = 180

[[colors.indexed_colors]]
color = "#111a20"
index = 181

[[colors.indexed_colors]]
color = "#18242c"
index = 182

[[colors.indexed_colors]]
color = "#324552"
index = 183

[[colors.indexed_colors]]
color = "#9f5f50"
index = 184

[[colors.indexed_colors]]
color = "#20141f"
index = 185

[[colors.indexed_colors]]
color = "#2c1c2b"
index = 186

[[colors.indexed_colors]]
color = "#523a50"
index = 187

[[colors.indexed_colors]]
color = "#58ddb8"
index = 188

[[colors.indexed_colors]]
color = "#151720"
index = 189

[[colors.indexed_colors]]
color = "#1e202c"
index = 190

[[colors.indexed_colors]]
color = "#323545"
index = 191

[[colors.indexed_colors]]
color = "#9b8d7a"
index = 192


[[colors.indexed_colors]]
color = "#958293"
index = 193

[[colors.indexed_colors]]
color = "#77988a"
index = 194

[[colors.indexed_colors]]
color = "#272628"
index = 195

[[colors.indexed_colors]]
color = "#333334"
index = 196

[[colors.indexed_colors]]
color = "#5a5a5a"
index = 197

[[colors.indexed_colors]]
color = "#150d20"
index = 198

[[colors.indexed_colors]]
color = "#1d132c"
index = 199

[[colors.indexed_colors]]
color = "#392952"
index = 200

[[colors.indexed_colors]]
color = "#201720"
index = 201

[[colors.indexed_colors]]
color = "#2c212c"
index = 202

[[colors.indexed_colors]]
color = "#453745"
index = 203

[[colors.indexed_colors]]
color = "#7ea7be"
index = 204

[[colors.indexed_colors]]
color = "#201d17"
index = 205

[[colors.indexed_colors]]
color = "#2c2821"
index = 206

[[colors.indexed_colors]]
color = "#454037"
index = 207

[[colors.indexed_colors]]
color = "#201811"
index = 208

[[colors.indexed_colors]]
color = "#2c2218"
index = 209

[[colors.indexed_colors]]
color = "#524232"
index = 210

[[colors.indexed_colors]]
color = "#97c1c1"
index = 211

[[colors.indexed_colors]]
color = "#a59588"
index = 212

[[colors.indexed_colors]]
color = "#98877a"
index = 213

[[colors.indexed_colors]]
color = "#867467"
index = 214

[[colors.indexed_colors]]
color = "#79817b"
index = 215

[[colors.indexed_colors]]
color = "#a4c7ca"
index = 216

[[colors.indexed_colors]]
color = "#9ec0c2"
index = 217

[[colors.indexed_colors]]
color = "#848d87"
index = 218

[[colors.indexed_colors]]
color = "#879089"
index = 219

[[colors.indexed_colors]]
color = "#8eacae"
index = 220

[[colors.indexed_colors]]
color = "#c6baae"
index = 221

[[colors.indexed_colors]]
color = "#7d8880"
index = 222

[[colors.indexed_colors]]
color = "#96829d"
index = 223

[[colors.indexed_colors]]
color = "#a4607c"
index = 224

[[colors.indexed_colors]]
color = "#111120"
index = 225

[[colors.indexed_colors]]
color = "#18182c"
index = 226

[[colors.indexed_colors]]
color = "#323252"
index = 227

[[colors.indexed_colors]]
color = "#70afca"
index = 228

[[colors.indexed_colors]]
color = "#df9eae"
index = 229

[[colors.indexed_colors]]
color = "#324252"
index = 230

[[colors.indexed_colors]]
color = "#56789a"
index = 231

[[colors.indexed_colors]]
color = "#557b99"
index = 232

[[colors.indexed_colors]]
color = "#201a17"
index = 233

[[colors.indexed_colors]]
color = "#2c2421"
index = 234

[[colors.indexed_colors]]
color = "#453b37"
index = 235

[[colors.indexed_colors]]
color = "#8bb5a9"
index = 236

[[colors.indexed_colors]]
color = "#171c20"
index = 237

[[colors.indexed_colors]]
color = "#21272c"
index = 238

[[colors.indexed_colors]]
color = "#373f45"
index = 239

[[colors.indexed_colors]]
color = "#b6564a"
index = 240

[[colors.indexed_colors]]
color = "#5fb0d1"
index = 241

[[colors.indexed_colors]]
color = "#323f52"
index = 242

[[colors.indexed_colors]]
color = "#7992a3"
index = 243

[[colors.indexed_colors]]
color = "#466f7d"
index = 244

[[colors.indexed_colors]]
color = "#669db2"
index = 245

[[colors.indexed_colors]]
color = "#65a6b1"
index = 246

[[colors.indexed_colors]]
color = "#61acbf"
index = 247

[[colors.indexed_colors]]
color = "#74a6b4"
index = 248

[[colors.indexed_colors]]
color = "#111520"
index = 249

[[colors.indexed_colors]]
color = "#181e2c"
index = 250

[[colors.indexed_colors]]
color = "#323c52"
index = 251

[[colors.indexed_colors]]
color = "#608e9a"
index = 252

[[colors.indexed_colors]]
color = "#171920"
index = 253

[[colors.indexed_colors]]
color = "#21232c"
index = 254

[[colors.indexed_colors]]
color = "#373a45"
index = 255
