live_config_reload = true

[cursor]
unfocused_hollow = false

[font]
size = 7.5

[font.bold]
family = "SFMono"
style = "Heavy"

[font.glyph_offset]
y = 0

[font.normal]
family = "SFMono"
style = "Regular"

[window]
opacity = 0.98

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 15
y = 10
#tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#101314"
foreground = "#cdd3d8"

[colors.bright]
black = "#2c3e3e"
blue = "#a3daf6"
cyan = "#5daeb3"
green = "#b8c1a1"
magenta = "#a475c3"
red = "#b07989"
white = "#cdd8d3"
yellow = "#cfa55f"

[colors.normal]
black = "#2c3e3e"
blue = "#a3daf6"
cyan = "#5daeb3"
green = "#b8c1a1"
magenta = "#a475c3"
red = "#b07989"
white = "#cdd8d3"
yellow = "#cfa55f"

[[colors.indexed_colors]]
color = "#B3836B"
index = 16

[[colors.indexed_colors]]
color = "#8fa398"
index = 17

[[colors.indexed_colors]]
color = "#7FA891"
index = 18

[[colors.indexed_colors]]
color = "#89b2a8"
index = 19

[[colors.indexed_colors]]
color = "#807773"
index = 20

[[colors.indexed_colors]]
color = "#5f6a73"
index = 21

[[colors.indexed_colors]]
color = "#756367"
index = 22

[[colors.indexed_colors]]
color = "#b2adae"
index = 23

[[colors.indexed_colors]]
color = "#1a1f20"
index = 24

[[colors.indexed_colors]]
color = "#252b2c"
index = 25

[[colors.indexed_colors]]
color = "#3d4445"
index = 26

[[colors.indexed_colors]]
color = "#c8a789"
index = 27

[[colors.indexed_colors]]
color = "#191720"
index = 28

[[colors.indexed_colors]]
color = "#23212c"
index = 29

[[colors.indexed_colors]]
color = "#3a3745"
index = 30

[[colors.indexed_colors]]
color = "#f2b599"
index = 31

[[colors.indexed_colors]]
color = "#201e1f"
index = 32

[[colors.indexed_colors]]
color = "#2c2a2b"
index = 33

[[colors.indexed_colors]]
color = "#454545"
index = 34

[[colors.indexed_colors]]
color = "#ad7361"
index = 35

[[colors.indexed_colors]]
color = "#0d201f"
index = 36

[[colors.indexed_colors]]
color = "#132c2b"
index = 37

[[colors.indexed_colors]]
color = "#214544"
index = 38

[[colors.indexed_colors]]
color = "#d45957"
index = 39

[[colors.indexed_colors]]
color = "#1c1c20"
index = 40

[[colors.indexed_colors]]
color = "#28282c"
index = 41

[[colors.indexed_colors]]
color = "#424245"
index = 42

[[colors.indexed_colors]]
color = "#e34e68"
index = 43

[[colors.indexed_colors]]
color = "#172020"
index = 44

[[colors.indexed_colors]]
color = "#212c2c"
index = 45

[[colors.indexed_colors]]
color = "#374545"
index = 46

[[colors.indexed_colors]]
color = "#a07479"
index = 47

[[colors.indexed_colors]]
color = "#0c201f"
index = 48

[[colors.indexed_colors]]
color = "#112c2b"
index = 49

[[colors.indexed_colors]]
color = "#1e4544"
index = 50

[[colors.indexed_colors]]
color = "#dd5d64"
index = 51

[[colors.indexed_colors]]
color = "#0f1720"
index = 52

[[colors.indexed_colors]]
color = "#15202c"
index = 53

[[colors.indexed_colors]]
color = "#243445"
index = 54

[[colors.indexed_colors]]
color = "#ca7b7c"
index = 55

[[colors.indexed_colors]]
color = "#191f20"
index = 56

[[colors.indexed_colors]]
color = "#232b2c"
index = 57

[[colors.indexed_colors]]
color = "#3a4445"
index = 58

[[colors.indexed_colors]]
color = "#ac8e75"
index = 59

[[colors.indexed_colors]]
color = "#191d20"
index = 60

[[colors.indexed_colors]]
color = "#23282c"
index = 61

[[colors.indexed_colors]]
color = "#3a4045"
index = 62

[[colors.indexed_colors]]
color = "#9e8f80"
index = 63

[[colors.indexed_colors]]
color = "#1f2020"
index = 64

[[colors.indexed_colors]]
color = "#2c2c2c"
index = 65

[[colors.indexed_colors]]
color = "#be5879"
index = 66

[[colors.indexed_colors]]
color = "#121a20"
index = 67

[[colors.indexed_colors]]
color = "#1a242c"
index = 68

[[colors.indexed_colors]]
color = "#2c3a45"
index = 69

[[colors.indexed_colors]]
color = "#f05171"
index = 70

[[colors.indexed_colors]]
color = "#1e1e20"
index = 71

[[colors.indexed_colors]]
color = "#2a2a2c"
index = 72

[[colors.indexed_colors]]
color = "#d15cb4"
index = 73

[[colors.indexed_colors]]
color = "#cdb3af"
index = 74

[[colors.indexed_colors]]
color = "#1d1c20"
index = 75

[[colors.indexed_colors]]
color = "#29282c"
index = 76

[[colors.indexed_colors]]
color = "#434245"
index = 77

[[colors.indexed_colors]]
color = "#c8929c"
index = 78

[[colors.indexed_colors]]
color = "#ffb771"
index = 79

[[colors.indexed_colors]]
color = "#201d19"
index = 80

[[colors.indexed_colors]]
color = "#2c2823"
index = 81

[[colors.indexed_colors]]
color = "#45403a"
index = 82

[[colors.indexed_colors]]
color = "#c7ae84"
index = 83

[[colors.indexed_colors]]
color = "#201e1e"
index = 84

[[colors.indexed_colors]]
color = "#2c2a2a"
index = 85

[[colors.indexed_colors]]
color = "#d3bd72"
index = 86

[[colors.indexed_colors]]
color = "#121520"
index = 87

[[colors.indexed_colors]]
color = "#1a1e2c"
index = 88

[[colors.indexed_colors]]
color = "#2c3245"
index = 89

[[colors.indexed_colors]]
color = "#feb672"
index = 90

[[colors.indexed_colors]]
color = "#ffb871"
index = 91

[[colors.indexed_colors]]
color = "#1c2020"
index = 92

[[colors.indexed_colors]]
color = "#282c2c"
index = 93

[[colors.indexed_colors]]
color = "#424545"
index = 94

[[colors.indexed_colors]]
color = "#ff858f"
index = 95

[[colors.indexed_colors]]
color = "#20201c"
index = 96

[[colors.indexed_colors]]
color = "#2c2c28"
index = 97

[[colors.indexed_colors]]
color = "#454542"
index = 98

[[colors.indexed_colors]]
color = "#cf7277"
index = 99

[[colors.indexed_colors]]
color = "#171720"
index = 100

[[colors.indexed_colors]]
color = "#21212c"
index = 101

[[colors.indexed_colors]]
color = "#373745"
index = 102

[[colors.indexed_colors]]
color = "#bc626a"
index = 103

[[colors.indexed_colors]]
color = "#201c20"
index = 104

[[colors.indexed_colors]]
color = "#2c282c"
index = 105

[[colors.indexed_colors]]
color = "#454245"
index = 106

[[colors.indexed_colors]]
color = "#7ec197"
index = 107

[[colors.indexed_colors]]
color = "#201f20"
index = 108

[[colors.indexed_colors]]
color = "#e2557c"
index = 109

[[colors.indexed_colors]]
color = "#aca979"
index = 110

[[colors.indexed_colors]]
color = "#1f1f20"
index = 111

[[colors.indexed_colors]]
color = "#201212"
index = 112

[[colors.indexed_colors]]
color = "#2c1a1a"
index = 113

[[colors.indexed_colors]]
color = "#523636"
index = 114

[[colors.indexed_colors]]
color = "#a2c89a"
index = 115


[[colors.indexed_colors]]
color = "#152020"
index = 116

[[colors.indexed_colors]]
color = "#1e2c2c"
index = 117

[[colors.indexed_colors]]
color = "#3d5252"
index = 118

[[colors.indexed_colors]]
color = "#5daeb3"
index = 119


[[colors.indexed_colors]]
color = "#435252"
index = 120

[[colors.indexed_colors]]
color = "#799ec3"
index = 121


[[colors.indexed_colors]]
color = "#1f201f"
index = 122

[[colors.indexed_colors]]
color = "#525252"
index = 123


[[colors.indexed_colors]]
color = "#4a5152"
index = 124
