#!/usr/bin/env bash

readonly ID_PREVIEW="preview"
fifo=/tmp/vifm_image_preview.fifo

if [ -e $fifo ]; then
    if [[ "$1" == "draw" ]]; then
		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
		[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
			[path]="${PWD}/$6") \
			> $fifo
	else
		declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
			> $fifo
	fi
fi
