#!/bin/bash

fifo=/tmp/vifm_image_preview.fifo
id=$(printf "0x%.8x" $(xdotool getactivewindow))
server=$(wmctrl -l | awk '$1 == "'$id'" { print $NF }')

close_preview() {
	rm $fifo
	killall ueberzug
}

[[ -e $fifo ]] || mkfifo $fifo
trap close_preview EXIT

tail -f $fifo | ueberzug layer --silent --parser bash &

vifm --server-name $server $@
