#!/bin/bash

only=$(vifm --remote-expr "layoutis('only')")

if((only)); then
	read width height <<< "$(wmctrl -lG | awk '$NF == "vifm" { print $5, $6 }')"
	((height > width)) && command=sp || command=vs
	[[ $1 =~ ^OPEN_DIRECTORY ]] && command+=" ${@#* }"
	[[ $1 =~ ^view ]] && command+=" | view!"
else
	[[ $1 =~ ^view ]] && command="view | "
	command+=only
fi

vifm --remote -c "$command"
