#!/bin/bash

case $1 in
	*dir)
		for tail in "${@:2}"; do
			tails+="$tail"
			[[ "$tail" != "${@: -1}" ]] && tails+=,
		done

		[[ ! $1 =~ ^set ]] &&
			flag=M modify=${1%%_*}

		~/.orw/scripts/wallctl.sh -${flag-d} $modify "$tails";;
	*wall)
		~/.orw/scripts/wallctl.sh -s "${@:2}"
esac
