#!/bin/bash

image="$1"

#separator=" ┃ "
separator=" | "

#image_size=$(file -b "$image" | awk -F '[x,]' '{ f = ("'${image##*.}'" == "png") ? 2 : NF - 2; print $f "x" $(f + 1) }')

image_size=$(du -h "$image" | cut -f1)
#image_dimensions=$(file "$image" | sed "s/.* \([0-9]*x[0-9]*\).*/\1/")
#image_dimensions=$(exiv2 "$image" 2> /dev/null | awk -F ':' '/Image size/ {print $2}')
image_dimensions=$(file -b "$image" | awk -F '[x,]' '{ f = ("'${image##*.}'" == "png") ? 2 : NF - 2; print $f "x" $(f + 1) }')

echo "$image_size$separator$image_dimensions$separator${image##*/}"
